---
abstract: 'simple in-memory access to RPM cpio archive'
author:
  - 'Alexey Tourbin <at@altlinux.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RPM-Payload
no_index:
  directory:
    - t
    - inc
requires: {}
version: 0.11
